apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "msal-proxy.fullname" . }}
  labels:
    {{- include "msal-proxy.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "msal-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "msal-proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "msal-proxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ .Values.volumeName }}
          persistentVolumeClaim:
            claimName: {{ .Values.claimName }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
             -  name: Logging__LogLevel__Default
                value: {{ .Values.env.LogLevel }}
             -  name: ForceHttps
                value: "{{ .Values.env.ForceHttps }}"
             -  name: EasyAuthForK8s__DataProtectionFileLocation
                value: {{ .Values.env.EasyAuthForK8sSigninPath }}                
             -  name: EasyAuthForK8s__SigninPath
                value: "{{ .Values.env.EasyAuthForK8sSigninPath }}"
             -  name: EasyAuthForK8s__AuthPath
                value: {{ .Values.env.EasyAuthForK8sAuthPath }}
             -  name: EasyAuthForK8s__AllowBearerToken
                value: "{{ .Values.env.EasyAuthForK8sAllowBearerToken }}"
             -  name: EasyAuthForK8s__DefaultRedirectAfterSignin
                value: "{{ .Values.env.EasyAuthForK8sDefaultRedirectAfterSignin }}"                
             -  name: AzureAd__Instance
                value: {{ .Values.env.AzureAdInstance }}
             -  name: AzureAd__Domain
                value: {{ .Values.env.AzureAdDomain }}
             -  name: AzureAd__CallbackPath
                value: {{ .Values.env.AzureAdCallbackPath }}
             -  name: AzureAd__SignedOutCallbackPath
                value: {{ .Values.env.AzureAdSignedOutCallbackPath }}                
             -  name: AzureAd__TenantId
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.env.AzureAdTenantIdKeyRefName }}
                    key: {{ .Values.env.AzureAdTenantIdKeyRefKey }}
             -  name: AzureAd__ClientId
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.env.AzureAdClientIdKeyRefName }}
                    key: {{ .Values.env.AzureAdClientIdKeyRefKey }}
             -  name: AzureAd__ClientSecret
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.env.AzureAdClientSecretKeyRefName }}
                    key: {{ .Values.env.AzureAdClientSecretKeyRefKey }}
          volumeMounts:
          - mountPath: {{ .Values.env.DataProtectionFileLocation }}
            name: {{ .Values.volumeName }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
