apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Values.claimName }}
    namespace: {{ include "easyauth-proxy.namespace" . }}
spec:
    accessModes:
    - ReadWriteMany
    storageClassName: azurefile
    resources:
        requests:
            storage: 5Gi