apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name}}
  namespace: default
type: Opaque
data:
  {{ .Values.azureAd.clientSecretKeyRefKey}}: {{ .Values.secret.azureclientsecret | b64enc }}