apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuard-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/msal/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/msal/index?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-injected-aio,x-injected-name,x-injected-nameidentifier,x-injected-objectidentifier,x-injected-preferred_username,x-injected-tenantid,x-injected-uti"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "256k"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - msalrichter.eastus.cloudapp.azure.com
    secretName: msalrichter-tls
  rules:
  - host: msalrichter.eastus.cloudapp.azure.com
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: kuard-pod
            port:
              number: 8080
        
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: msal-proxy
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: msalrichter.eastus.cloudapp.azure.com
    http:
      paths:
      - path: /msal
        pathType: Prefix
        backend:
          service:
            name: msal-proxy
            port:
              number: 80
  tls:
  - hosts:
    - msalrichter.eastus.cloudapp.azure.com
    secretName: msalrichter-tls
