apiVersion: apps/v1
kind: Deployment
metadata:
  name: msal-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msal-proxy
  template:
    metadata:
      labels:
        app: msal-proxy
    spec:
      containers:
      -  image: "lesterjt/easyauthfork8s:latest"
         imagePullPolicy: Always
         name: msal-net-proxy
         env:
         -  name: DataProtectionFileLocation
            value: /mnt/dp
         -  name: ForceHttps
            value: "true"
         -  name: AzureAd__Instance
            value: https://login.microsoftonline.com/
         -  name: AzureAd__Domain
            value: microsoft.onmicrosoft.com
         -  name: AzureAd__TenantId
            value: 72f988bf-86f1-41af-91ab-2d7cd011db47
         -  name: AzureAd__ClientId
            value: ae837949-bc92-4573-aafb-95c657a7392c
         -  name: AzureAd__CallbackPath
            value: /msal/signin-oidc
         -  name: AzureAd__SignedOutCallbackPath
            value: /msal/signout-callback-oidc
         -  name: AzureAd__ClientSecret
            value: gZC5Ns1LDb_KimcB_3a9-SImyUNWbPrNOn
         -  name: Logging__LogLevel__Default
            value: Debug
         -  name: AllowedHosts
            value: "*"
         -  name: RedirectParam
            value: rd
         -  name: ShowLogin
            value: "false"    
         ports:
         - containerPort: 80
           protocol: TCP
         volumeMounts:
         - mountPath: "/mnt/dp"
           name: dpvol
      volumes:
      - name: dpvol
        persistentVolumeClaim:
          claimName: msal-net-proxy-az-file-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: msal-proxy
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: msal-proxy
