#!/bin/sh -x

echo "BEGIN @ $(date +"%T"): Deploy the Ingress Resources..."

sed "s/{{APP_HOSTNAME}}/$APP_HOSTNAME/g" ./TemplateFiles/kuard-ingress.yaml > ./AutoGeneratedFiles/kuard-ingress.yaml
sed -i "s/{{TLS_SECRET_NAME}}/$TLS_SECRET_NAME/g" ./AutoGeneratedFiles/kuard-ingress.yaml
kubectl apply -f ./AutoGeneratedFiles/kuard-ingress.yaml

echo "COMPLETE @ $(date +"%T"): Deploy the Ingress Resources"