#!/bin/sh -x

echo "BEGIN @ $(date +"%T"): Deploy the Ingress Resources..."

sed "s/{{APP_HOSTNAME}}/$APP_HOSTNAME/g" ./sample/templates/sample-ingress.yaml > ./AutoGeneratedFiles/sample-ingress.yaml
sed -i "s/{{TLS_SECRET_NAME}}/$TLS_SECRET_NAME/g" ./AutoGeneratedFiles/sample-ingress.yaml
kubectl apply -f ./AutoGeneratedFiles/sample-ingress.yaml

echo "COMPLETE @ $(date +"%T"): Deploy the Ingress Resources"