name: Check for Deprecated K8s APIs

on:
  schedule:
    - cron: '0 15 10 15 * ?'

jobs:  
  check_for_deprecated_APIs:
    name: Check Deprecated K8s APIs
    runs-on: macos-latest
    
    - name: Download Pluto
      uses: FairwindsOps/pluto/github-action@master

    - name: Use pluto
      run: |
        pluto detect-files -d ./charts/easyauth-proxy
        pluto detect-files -d ./