# This is a basic workflow to help you get started with Actions

name: Check deprecated APIs

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - dev

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  release:
    types: [published]

jobs:
  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install FairwindsOps/tap/pluto 
      # - run: pluto detect-files -d ./
      - run: helm template ./charts/msal-proxy | pluto detect -
