name: Build, test & push to multiple registries

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - dev

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    name: .NET restore, build & test

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Restore dependencies
      run: dotnet restore ./OCP.Msal.Proxy.Web/OCP.Msal.Proxy.Web.csproj
    - name: Build
      run: dotnet build ./OCP.Msal.Proxy.Web/OCP.Msal.Proxy.Web.csproj --no-restore
    - name: Test
      run: dotnet test OCP.Msal.Proxy.Tests/OCP.Msal.Proxy.Tests.csproj --no-build --verbosity normal 
  
  check_for_depreciated_APIs:
    name: Check Depreciated K8s APIs
    runs-on: macos-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v2
      - run: brew install FairwindsOps/tap/pluto 
      - run: pluto detect-files -d ./charts/msal-proxy
      
  push_to_registries:
  
    needs: check_for_depreciated_APIs
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USER_ID }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            ghcr.io/${{ github.repository }}/msal-net-proxy-opt
            easyauthfork8s/msal-net-proxy-opt
      
      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
