name: .NET

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Restore dependencies
      run: dotnet restore ./OCP.Msal.Proxy.Web/OCP.Msal.Proxy.Web.csproj
    - name: Build
      run: dotnet build ./OCP.Msal.Proxy.Web/OCP.Msal.Proxy.Web.csproj --no-restore
    - name: Test
      run: dotnet test OCP.Msal.Proxy.Tests/OCP.Msal.Proxy.Tests.csproj --no-build --verbosity normal 
