name: KubePug
# This workflow is triggered on pushes to the repository.
on: [push]
env:
  HELM_VERSION: "v3.2.4"
  K8S_TARGET_VERSION: "v1.16.0"

jobs:
 api-deprecations-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repo
        uses: actions/checkout@v2

      - name: Install Helm and Kubepug binaries
        run: |
          mkdir -p ~/bin
          curl -sSL https://github.com/rikatz/kubepug/archive/refs/tags/v1.2.1.tar.gz | tar xvfz - --overwrite -C ~/bin/
          curl -sSL https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz | tar xvfz - -C ~/bin/ --wildcards --strip 1 '*/helm'
      # nothing
      - name: Run Kubepug with your Helm Charts Repository
        run: |
          echo "current directory:" pwd
          echo "directory files:" ls
          echo "------------------------"
          find ~/work/EasyAuthForK8s/EasyAuthForK8s/charts -type d
