# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_main-sh:

    runs-on: ubuntu-latest
    name: Run main.sh script

    steps:
    - uses: actions/checkout@v2
    - name: Call the script
      run: bash ./main.sh -a msal-test-kgates2 -c easyauth-kgates2 -r easy-auth2 -e kgates@microsoft.com -d microsoft.com -l eastus
      
    
