# This is a basic workflow to help you get started with Actions

name: Check deprecated APIs

on:
  workflow_dispatch:

jobs:
  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install FairwindsOps/tap/pluto
      - run: helm template ./charts/msal-proxy | pluto detect -
      
      #pluto detect-files -d ./
