# This is a basic workflow to help you get started with Actions

name: Check deprecated APIs

on:
  workflow_dispatch:
    inputs:
      targetEnv:
        description: 'Target environment: dev, test, prod'     
        required: false
        default: 'dev' 

jobs:
  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install FairwindsOps/tap/pluto
      - run: helm template ./charts/msal-proxy --api-versions v1.16.0 | pluto detect -
      
      #pluto detect-files -d ./
